version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/api-example
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: "api-example"